{"uuid": "28d58e8d-31ef-4a61-9789-35948d23fa33", "children": ["bde9efb2-58c0-490c-a0ba-c1e31df1dad2"], "befores": [{"name": "manage_session", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\calvario31\\\\Documents\\\\Projects\\\\Selenium\\\\Python\\\\completeFramework\\\\tests\\\\resources\\\\logs\\\\appLog.log'\n", "trace": "  File \"C:\\Users\\calvario31\\Documents\\Projects\\Selenium\\Python\\completeFramework\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\calvario31\\Documents\\Projects\\Selenium\\Python\\completeFramework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\calvario31\\Documents\\Projects\\Selenium\\Python\\completeFramework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\calvario31\\Documents\\Projects\\Selenium\\Python\\completeFramework\\conftest.py\", line 41, in manage_session\n    log_manager.log = log_manager.get_logger()\n  File \"C:\\Users\\calvario31\\Documents\\Projects\\Selenium\\Python\\completeFramework\\src\\utilities\\log_manager.py\", line 45, in get_logger\n    file_handler = logging.FileHandler(\"./tests/resources/logs/appLog.log\", mode='w', delay=False)\n  File \"C:\\Users\\calvario31\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1146, in __init__\n    StreamHandler.__init__(self, self._open())\n  File \"C:\\Users\\calvario31\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1175, in _open\n    return open(self.baseFilename, self.mode, encoding=self.encoding,\n"}, "start": 1631337561667, "stop": 1631337561667}], "start": 1631337561667, "stop": 1631337561796}